### ISSUE TITLE
panic: unknown cause

### ISSUE THREAD

**Issue by camc314** [oxc-project/tsgolint#288]
> I'm still seeing a crash here when enabling the rule with latest oxlint.
> 
> ```
> Error running tsgolint: "exit status: exit status: 2"%                                                                                                        
> ``` 

 _Originally posted by @skovhus in [#226](https://github.com/oxc-project/tsgolint/issues/226#issuecomment-3390526380)_

**Comment by camc314** [comment]
@skovhus do you mind re-running oxlint, and sharing the logs with `OXC_LOG=debug` (either here or in slack). We fixed a bug in the latest oxlint version that prevented the stderr output from being printed, which contains the logs neededed to debug this. 

Thanks

**Comment by skovhus** [comment]
Hey @camc314,

Just tested with latest `oxlint`, and it doesn't panic anymore when enabling `@typescript-eslint/unbound-method`. 👏🏼

**Comment by camc314** [comment]
great! thanks for checking

**Comment by skovhus** [comment]
Ah, damn my bad. I forgot to add `--type-aware`, it still crashes.

**Comment by camc314** [comment]
no worries, mind sharing the logs, and i'll take a look

**Comment by Lonami** [comment]
Reproducing this issue might involve importing from `.d.ts` files from a `.ts` file (I believe across packages perhaps with different tsconfig's that relative-import a "base" config and nothing else). The panic we were experiencing, which might not be the same as this issue but seems similar because we also had the same exit is:
https://github.com/oxc-project/tsgolint/blob/c9297b5983fec2ab986264308d5aa49b89af5074/internal/linter/linter.go#L111
I haven't personally been able to reproduce it, but have seen it occur on another person's Mac. Unfortunately the code is private and I seem unable to write a reproducer from Windows.

**Comment by camc314** [comment]
@Lonami mind making a new issue? thanks

Im going to close this one as stale, as no one has seen the exact issue above recently.

yours will probably be a different issue.

**Comment by Lonami** [comment]
Not confident opening one if I can't reproduce myself. I'll try to keep it in mind and open a new one if I find something concrete.

**Comment by camc314** [comment]
> Not confident opening one if I can't reproduce myself. I'll try to keep it in mind and open a new one if I find something concrete.

if you can share logs + tsconfigs and file structured 5£-5 should be enough for me to guess an issue - feel free to DM me on X or Discord if you're not comfortable sharing on here.
